<?php
return array(
	1	=>	"每日抽奖",
	2	=>	"new_item",
	3	=>	"添加空地",
	4	=>	"删除空地",
	5	=>	"帮忙好友5次",
	6	=>	"帮忙好友建设",
	7	=>	"兑换金块",
	8	=>	"批量移动",
	9	=>	"批量收租",
	10	=>	"批量签约",
	11	=>	"解除锁定",
	12	=>	"first_visit",
	13	=>	"BUY收藏品",
	14	=>	"KEEP收藏品",
	15	=>	"SEND收藏品",
	16	=>	"GET_REWARD hq",
	17	=>	"扩地",
	18	=>	"更新任务",
	19	=>	"new_mode",
	20	=>	"new_state",
	21	=>	"destroy",
	22	=>	"move",
	23	=>	"upd_suspended",
	24	=>	"GET_REWARD plane",
	25	=>	"GET_REWARD set",
	26	=>	"今日红包",
);